version: "3.9"
services:
  app:
    build: .
    image: custom_ros_image:latest
    container_name: ros-container

    user: "ros"

    network_mode: "host"
    ipc: "host"

    stdin_open: true
    tty: true

  # ✅ GPU support (NVIDIA)
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    # ✅ Required for NVIDIA runtime
    runtime: nvidia

    volumes:
      # Target ROS package directory
      - ./config:/home/ros/dev_ws/src/my_bot/config
      - ./description:/home/ros/dev_ws/src/my_bot/description
      - ./launch:/home/ros/dev_ws/src/my_bot/launch
      - ./worlds:/home/ros/dev_ws/src/my_bot/worlds

      - ./CMakeLists.txt:/home/ros/dev_ws/src/my_bot/CMakeLists.txt
      - ./package.xml:/home/ros/dev_ws/src/my_bot/package.xml

      # X11 for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all